### PR TITLE
Remove the extra conversion factor from roughness.

### PR DESCRIPTION
**Pull request by alarshi**
The PR fixes a bug in the grain size reduction (most likely introduced by me) . Based on the eq.8 in the paper, `dr/dt` would be `dR/dt * roughness_to_grain_size_conversion`, where r is roughness and R is grain size. Since grain size reduction term is `r^2`, we only need one `roughness_to_grain_size_conversion` factor to write the equation in terms of grain_size. This also gives very similar results with our notebook computing the equilibrium_grain_size.

### CODE REVIEW

**Comment by gassmoeller** [comment]
This changes our test results. Have you checked if the new result for these tests is better than the old one? I am just wondering why we didnt notice this in the existing tests that compute the grain size change rate over time for a given strain rate.

**Comment by alarshi** [comment]
I agree. I think it is because we were comparing our notebook result with the aspect result and both did not have the right grain size reduction (if we agree on this change). We can discuss more today.

**Comment by alarshi** [comment]
The latest commit should hopefully fix the failing tests. I also checked that the updated notebook result (0.015124 m) is  consistent with the aspect result from this branch after running the test for ~170 Ma, (0.1508 m) .

**Review by gassmoeller — APPROVED** [review]
Great, ready to go.

**Pull request merged**
