### PR TITLE
Added parameters from the paper.

### PR DESCRIPTION
**Pull request by alarshi**
This PR adds the parameter values from the Mulyukova and Bercovici (2018) paper. We want to reproduce the results of Fig 4 from their paper (constant stress and temperature conditions). Currently, this test does not work because the boundary conditions are not incorrect. I need to discuss this further to fix it.

### For new features/models or changes of existing features:

* [ ] I have tested my new feature locally to ensure it is correct.

### CODE REVIEW

**Comment by jdannberg** [comment]
I changed your setup to be simple shear (see below) and I think that works much better, at least you can see that if you increase the resolution again, the stresses are constant throughout the model. I also had to adapt some other things, notably:
- minimum grain size (default is 1e-5 which is too large)
- this is a nonlinear problem, so it should use the nonlinear solver
- I decreased the resolution to make the model run fast

There are still some problems, for example, the nonlinear solver does not converge, and we do get different results compared to Mulyukova & Bercovici in terms of the time scale and the absolute values of the grain size, so we still need to figure out what's wrong with that. But this already gives us the same pattern they get in the paper. 
[plot.pdf](https://github.com/grain-damage-Mulyukova/aspect/files/11142717/plot.pdf)

```
# A test for the grain size material model using pinned state damage formulation. 
# This test uses the parameters from Mulyukova and Bercovici (2018) at constant 
# temperature and stress in their figure 4 setup.

#include grain_size_strain.prm
set Dimension                              = 2
set End time                               = 3e8
set Output directory                       = output-mulyukova-bercovici
set Use years in output instead of seconds = true
set Maximum time step                      = 1e5
set Nonlinear solver scheme                = iterated Advection and Stokes

set Surface pressure                       = 0
set Adiabatic surface temperature          = 1100

subsection Geometry model
  set Model name = box

  subsection Box
    set X extent = 100000
    set Y extent = 100000
    set X periodic = true
  end
end


subsection Boundary temperature model
  set Fixed temperature boundary indicators   = top,bottom
end

subsection Boundary temperature model
  set List of model names = initial temperature
  subsection Initial temperature
    set Minimal temperature = 1100
  end
end

subsection Boundary composition model
  set List of model names = initial composition
end

subsection Gravity model
  set Model name = vertical
  subsection Vertical
    set Magnitude = 0.0
  end
end

subsection Boundary traction model
  set Prescribed traction boundary indicators = top x: function, bottom x: function # pressure bc: Prescribe a horizontal traction on the left boundary and vertical traction on the top boundary
end

subsection Boundary traction model
  subsection Function
    set Variable names = x,y
    set  Function constants = pressure = 35.355339059e6, y_extent = 1e5
    # This is sqrt(50e6^2/2)
    # We want to prescribe a pressure of 50 at the left boundary
    # and -50 at the top boundary.
    # The traction in this case is defined as:
    # tau =  - pressure * normal_vector.
    # On the left boundary, the outward pointing normal vector is
    # (-1;0). On the top (0;1).
    # Therefore:
    # Left boundary:  tau = - pressure(left) (-1;0) = - (50) (-1;0) = (50;0).
    # Top boundary: tau   = - pressure(top) (0;1) = - (50) (0;1) = (0;-50).
    set Function expression = if (y>y_extent/2, pressure, -pressure)  ;  0
  end
end


subsection Boundary velocity model
  set Prescribed velocity boundary indicators = top y: function, bottom y: function 

  subsection Function
    set Variable names = x,y
    set Function expression = 0;0
  end
end


subsection Initial temperature model
  set Model name = adiabatic

  subsection Adiabatic
    set Age top boundary layer      = 0
    subsection Function
      set Function expression       = 0
    end
  end
end

subsection Initial composition model
  set Model name = function

  subsection Function
    set Variable names      = x,z
    set Function constants  =
    set Function expression = 7e-3
  end
end

subsection Compositional fields
  set Number of fields = 1
  set Names of fields   = grain_size
end


subsection Material model
  set Model name = grain size

  subsection Grain size model
    set Reference density                = 3400
    set Thermal conductivity             = 0
    set Thermal expansion coefficient    = 0
    set Reference compressibility        = 0
    set Viscosity                        = 1e18
    set Minimum viscosity                = 1e16
    set Reference temperature            = 1100
    set Recrystallized grain size        =

    set Grain growth activation energy       = 3e5
    set Grain growth activation volume       = 0.0
    set Grain growth rate constant           = 1.6E-022
    set Grain growth exponent                = 4
    set Average specific grain boundary energy = 1.0
    set Geometric constant                   = 3
    set Grain size evolution formulation     = pinned grain damage

    # Mulyukova and Bercovici (2018)
    # Diffusion creep
    set Diffusion creep prefactor            =13.6e-24 # s^-1 Pa^-1 m^p
    set Diffusion creep exponent             =1.0 # 1 for diffusion creep
    set Diffusion creep grain size exponent  =3
    set Diffusion activation energy          =3e5 #J/mol
    set Diffusion activation volume          =0 # m^3/mol

    set Dislocation viscosity iteration threshold = 1e-3
    # Dislocation creep
    set Dislocation creep prefactor          =1.1e-13 # s^-1 Pa^-n
    set Dislocation creep exponent           =3
    set Dislocation activation energy        =530000 # J/mol
    set Dislocation activation volume        =0 # m^3/mol
    
    set Minimum grain size                   = 1e-8

    subsection Grain damage partitioning
      set Minimum grain size reduction work fraction = 5e-3
      set Maximum grain size reduction work fraction = 5e-3
    end
  end
end

subsection Mesh refinement
  set Initial adaptive refinement        = 0
  set Initial global refinement          = 0
  set Time steps between mesh refinement = 0
end

subsection Postprocess
  set List of postprocessors = composition statistics,temperature statistics, velocity statistics, visualization
  subsection Visualization
    set List of output variables = viscosity, shear stress, stress
    set Time steps between graphical output = 10
  end
end

subsection Nullspace removal
  set Remove nullspace = net x translation
end
```

**Comment by alarshi** [comment]
Oh this is cool, the grain size evolution trend is really similar to the paper! I double checked the parameter values from the paper and the input file, but did not find any obvious difference on why the time and grain size would be different. I will think more about this before our meeting.

**Comment by jdannberg** [comment]
I had one more idea. I think the diffusion and dislocation creep prefactors need to be scaled by a factor of 2^n with n being the stress exponent for each mechanisms (so 2^1 for diffusion creep and 2^3 for dislocation creep). That is because their definition of the prefactor is different (see their equations 2 and 3 and compare these to what we have in the material model; we do not have these factors of 2 that A and B are scaled with). 

That gets us closer to the right solution, but the results are still different.

**Comment by jdannberg** [comment]
Another thing that we could test would be to compute the equilibrium grain size with the equation we have in the overleaf document and see if that agrees with either our computation or the value in the paper.

**Comment by alarshi** [comment]
I actually did not understand the scaling of prefactors for diffusion and dislocation creep with 2^n, but we can discuss this on Monday. With the current values, our grain size at transition from diffusion to dislocation creep is similar to the values given in the paper, 1.605e-05 m, which is nice :) 
Still cannot figure out why the viscosities and the timing of plunge are different :-/

**Comment by alarshi** [comment]
I have pushed the changes to our parameter file that gives consistent results with our notebook. This includes the updates by @jdannberg  to give constant stress and changes to the prefactors.

Here is the output for grain size with time for starting grain size of 1e-2 (green) and 1e-4 (magenta).

image

**Comment by alarshi** [comment]
I have rebased this branch to `grain_damage_formulation` , hopefully it works now.

**Review by gassmoeller — APPROVED** [review]
Thanks for rebasing. I think I found a version of the parameter file that comes closer to the paper results (only changing the time stepping scheme and nonlinear iterations, similar to what @jdannberg said today). I will merge this PR, then rebase to the main ASPECT and add my changes there.

**Pull request merged**
